sudo: required
dist: trusty

services:
  - docker

language: cpp

env:
  matrix:
    - COMPILER=gcc

before_install:
  - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install cvmfs cvmfs-config-default
  - rm -f cvmfs-release-latest_all.deb
  - wget https://desy.de/~ebrianne/default.local
  - sudo mkdir -p /etc/cvmfs
  - sudo mv default.local /etc/cvmfs/default.local
  - sudo /etc/init.d/autofs stop
  - sudo cvmfs_config setup
  - sudo mkdir -p /cvmfs/dune.opensciencegrid.org
  - sudo mount -t cvmfs dune.opensciencegrid.org /cvmfs/dune.opensciencegrid.org
  - ls /cvmfs/dune.opensciencegrid.org
  - sudo mkdir -p /cvmfs/fermilab.opensciencegrid.org
  - sudo mount -t cvmfs fermilab.opensciencegrid.org /cvmfs/fermilab.opensciencegrid.org
  - ls /cvmfs/fermilab.opensciencegrid.org
  - sudo mkdir -p /cvmfs/larsoft.opensciencegrid.org
  - sudo mount -t cvmfs larsoft.opensciencegrid.org /cvmfs/larsoft.opensciencegrid.org
  - ls /cvmfs/larsoft.opensciencegrid.org

# command to install dependencies
install:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package
  - export description=`date`

# command to run tests
script:
  - docker run -it --name CI_container -v $PKGDIR:/Package -e COMPILER=$COMPILER -v /cvmfs/larsoft.opensciencegrid.org:/cvmfs/larsoft.opensciencegrid.org -v /cvmfs/dune.opensciencegrid.org:/cvmfs/dune.opensciencegrid.org -v /cvmfs/fermilab.opensciencegrid.org:/cvmfs/fermilab.opensciencegrid.org -d clicdp/slc6-build /bin/bash
  - docker exec -it CI_container /bin/bash -c "./Package/.travis-ci.d/compile_and_test.sh"

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
